insert into Constraints (field, data) values ('1_minus_mark','2' )
insert into Constraints (field, data) values ('2_plus_mark', '5')
insert into Constraints (field, data) values ('3_rules', 'Rules goes here')
insert into Constraints (field, data) values ('4_myhr', '1')
insert into Constraints (field, data) values ('5_mymin', '10')
insert into Constraints (field, data) values ('6_mysec', '20')
